# Generated by Django 4.0.2 on 2022-09-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0003_complain_remove_registration_image_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garbageapp.registration'),
        ),
    ]
