# Generated by Django 4.0.2 on 2022-09-06 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garbageapp', '0008_complain_creationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='bin',
        ),
        migrations.AddField(
            model_name='bin',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garbageapp.driver'),
        ),
        migrations.AddField(
            model_name='complain',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garbageapp.driver'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
