# Generated by Django 4.0.2 on 2022-09-06 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0004_complain_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('loadtype', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('bus', models.CharField(blank=True, max_length=100, null=True)),
                ('assign', models.CharField(blank=True, max_length=100, null=True)),
                ('complain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garbageapp.complain')),
            ],
        ),
    ]
