# Generated by Django 4.0.2 on 2022-09-06 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0007_remove_driver_user_driver_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 6, 17, 28, 32, 797656)),
            preserve_default=False,
        ),
    ]
