# Generated by Django 4.0.2 on 2022-09-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0009_remove_driver_bin_bin_driver_complain_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
