# Generated by Django 4.0.2 on 2022-09-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0010_complain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='complain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
