# Generated by Django 4.0.2 on 2022-09-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0011_complain_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='completed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='remaining',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
