# Generated by Django 4.0.2 on 2022-09-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0012_complain_completed_complain_remaining_complain_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='idname',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
    ]
