# Generated by Django 4.0.2 on 2022-09-13 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0015_trackinghistory_complain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='assign',
        ),
        migrations.AddField(
            model_name='bin',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
